name: CD Release

on:
  push:
    branches:
      - releases

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get crate version
        id: version
        run: echo ::set-output name=value::$(sed -ne 's/version = "\(.*\)"/\1/p' < Cargo.toml)

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.value }}
          release_name: Version ${{ steps.version.outputs.value }}
          draft: false
          prerelease: false
