name: CD Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get crate version
        id: version
        run: echo ::set-output name=value::$(sed -ne 's/^version = "\(.*\)"/\1/p' < Cargo.toml)

      - name: Get CHANGELOG entry
        id: changelog
        run: |
          body=$(python ci/changelog.py ${{ steps.version.outputs.value }})
          body="${body//$'\n'/'%0A'}"
          echo ::set-output name=body::$body

      - name: Tag branch
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.version.outputs.value }}
          message: v${{ steps.version.outputs.value }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        with:
          tag_name: v${{ steps.version.outputs.value }}
          name: Release v${{ steps.version.outputs.value }}
          body: ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
